# Generated by Django 2.2.18 on 2021-03-20 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoUrl', models.CharField(max_length=50)),
                ('thumbUrl', models.CharField(max_length=50)),
                ('coverUrl', models.CharField(max_length=50)),
                ('aspectRatio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
            options={
                'verbose_name': 'VideoInfo',
                'verbose_name_plural': 'VideoInfo',
                'db_table': '',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='FeedPosts',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=50)),
                ('postContent', models.TextField()),
                ('feedUploaderId', models.CharField(max_length=50)),
                ('postId', models.CharField(max_length=50)),
                ('postLikeCount', models.IntegerField()),
                ('userThumbnail', models.CharField(max_length=50)),
                ('postImage', models.CharField(max_length=50)),
                ('mediaType', models.BooleanField(default=False)),
                ('isPayable', models.BooleanField(default=False)),
                ('amount', models.CharField(max_length=50)),
                ('userContacts', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('postalCode', models.CharField(max_length=50)),
                ('shop', models.CharField(max_length=50)),
                ('shopLocation', models.CharField(max_length=50)),
                ('shopUrl', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('birthday', models.CharField(max_length=50)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.VideoInfo')),
            ],
            options={
                'verbose_name': 'FeedPosts',
                'verbose_name_plural': 'FeedPosts',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
