# Generated by Django 2.2.18 on 2021-03-20 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userPaidVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payerId', models.CharField(max_length=50)),
                ('checkoutRequestID', models.CharField(max_length=50)),
                ('paymenConfirmed', models.BooleanField()),
                ('mediaType', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feeds.FeedPosts')),
            ],
            options={
                'verbose_name': 'userPaidVideo',
                'verbose_name_plural': 'userPaidVideos',
                'db_table': '',
                'managed': True,
            },
        ),
    ]
