# Generated by Django 2.2.18 on 2021-03-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0002_userpaidvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpaidvideo',
            name='mediaType',
        ),
        migrations.AlterField(
            model_name='videoinfo',
            name='aspectRatio',
            field=models.DecimalField(decimal_places=4, max_digits=5),
        ),
    ]
